In [1]:
import numpy as np

In [2]:
a = 40
b = 70

In [3]:
a > b

False

In [4]:
cad = np.random.randint(15, 51, size = (15,10))
cad

array([[35, 32, 18, 49, 45, 17, 15, 35, 43, 27],
       [20, 28, 35, 42, 22, 44, 30, 22, 45, 15],
       [32, 18, 23, 35, 48, 26, 33, 38, 32, 17],
       [20, 22, 30, 21, 35, 36, 25, 47, 15, 26],
       [26, 37, 33, 37, 26, 18, 16, 40, 17, 41],
       [22, 31, 48, 48, 20, 45, 15, 31, 39, 27],
       [32, 36, 35, 45, 27, 50, 18, 15, 50, 28],
       [37, 37, 49, 28, 49, 31, 49, 39, 27, 17],
       [41, 16, 18, 37, 49, 44, 21, 47, 29, 24],
       [19, 46, 23, 35, 39, 36, 21, 40, 20, 48],
       [33, 35, 44, 37, 41, 28, 34, 38, 37, 48],
       [30, 20, 17, 46, 30, 19, 23, 44, 38, 34],
       [36, 44, 32, 19, 36, 42, 35, 46, 42, 34],
       [16, 39, 27, 18, 33, 41, 38, 16, 32, 35],
       [44, 48, 37, 23, 18, 16, 47, 38, 19, 17]])

In [5]:
type(cad)

numpy.ndarray

In [6]:
cad_18 = cad > 18
cad_18

array([[ True,  True, False,  True,  True, False, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True, False, False,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [ True, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True, 

In [9]:
cad[cad_18] # pega todos os valores que são maiores de 18 (condião dada pro cad_18)

array([35, 32, 49, 45, 35, 43, 27, 20, 28, 35, 42, 22, 44, 30, 22, 45, 32,
       23, 35, 48, 26, 33, 38, 32, 20, 22, 30, 21, 35, 36, 25, 47, 26, 26,
       37, 33, 37, 26, 40, 41, 22, 31, 48, 48, 20, 45, 31, 39, 27, 32, 36,
       35, 45, 27, 50, 50, 28, 37, 37, 49, 28, 49, 31, 49, 39, 27, 41, 37,
       49, 44, 21, 47, 29, 24, 19, 46, 23, 35, 39, 36, 21, 40, 20, 48, 33,
       35, 44, 37, 41, 28, 34, 38, 37, 48, 30, 20, 46, 30, 19, 23, 44, 38,
       34, 36, 44, 32, 19, 36, 42, 35, 46, 42, 34, 39, 27, 33, 41, 38, 32,
       35, 44, 48, 37, 23, 47, 38, 19])

In [8]:
len(cad[cad_18])

127

In [11]:
cad_18.sum() # valores booleanos tomam a forma de 0 (False) e 1 (True). Quando somar todos, dá a soma de todos True

127

In [12]:
cad[2]

array([32, 18, 23, 35, 48, 26, 33, 38, 32, 17])

In [13]:
cad[cad > 25]

array([35, 32, 49, 45, 35, 43, 27, 28, 35, 42, 44, 30, 45, 32, 35, 48, 26,
       33, 38, 32, 30, 35, 36, 47, 26, 26, 37, 33, 37, 26, 40, 41, 31, 48,
       48, 45, 31, 39, 27, 32, 36, 35, 45, 27, 50, 50, 28, 37, 37, 49, 28,
       49, 31, 49, 39, 27, 41, 37, 49, 44, 47, 29, 46, 35, 39, 36, 40, 48,
       33, 35, 44, 37, 41, 28, 34, 38, 37, 48, 30, 46, 30, 44, 38, 34, 36,
       44, 32, 36, 42, 35, 46, 42, 34, 39, 27, 33, 41, 38, 32, 35, 44, 48,
       37, 47, 38])

In [14]:
len(cad[cad > 25])

105

In [15]:
dados_extraido = np.extract(cad > 25, cad) #Extrair elementos que satisfaçam uma determinada condição
dados_extraido

array([35, 32, 49, 45, 35, 43, 27, 28, 35, 42, 44, 30, 45, 32, 35, 48, 26,
       33, 38, 32, 30, 35, 36, 47, 26, 26, 37, 33, 37, 26, 40, 41, 31, 48,
       48, 45, 31, 39, 27, 32, 36, 35, 45, 27, 50, 50, 28, 37, 37, 49, 28,
       49, 31, 49, 39, 27, 41, 37, 49, 44, 47, 29, 46, 35, 39, 36, 40, 48,
       33, 35, 44, 37, 41, 28, 34, 38, 37, 48, 30, 46, 30, 44, 38, 34, 36,
       44, 32, 36, 42, 35, 46, 42, 34, 39, 27, 33, 41, 38, 32, 35, 44, 48,
       37, 47, 38])

In [16]:
len(dados_extraido)

105